// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbgB5WnOhH2BWljGV-BHcGelwMyLge8NQ',
    appId: '1:1033465264392:web:ac7b84a270bcfafe6054bd',
    messagingSenderId: '1033465264392',
    projectId: 'fierbace-project',
    authDomain: 'fierbace-project.firebaseapp.com',
    storageBucket: 'fierbace-project.firebasestorage.app',
    measurementId: 'G-L19BKP7FKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxWrGP5RsGk_dGQAC8Df0sAmSfGHDz6FU',
    appId: '1:1033465264392:android:22e31eefbfbf72146054bd',
    messagingSenderId: '1033465264392',
    projectId: 'fierbace-project',
    storageBucket: 'fierbace-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnZfDRw7T9ck6U6GTILQ31ZKS2uVZljHQ',
    appId: '1:1033465264392:ios:506e62036ac2382e6054bd',
    messagingSenderId: '1033465264392',
    projectId: 'fierbace-project',
    storageBucket: 'fierbace-project.firebasestorage.app',
    iosBundleId: 'com.example.dioProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnZfDRw7T9ck6U6GTILQ31ZKS2uVZljHQ',
    appId: '1:1033465264392:ios:506e62036ac2382e6054bd',
    messagingSenderId: '1033465264392',
    projectId: 'fierbace-project',
    storageBucket: 'fierbace-project.firebasestorage.app',
    iosBundleId: 'com.example.dioProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbgB5WnOhH2BWljGV-BHcGelwMyLge8NQ',
    appId: '1:1033465264392:web:d3ba4b9505b9e60d6054bd',
    messagingSenderId: '1033465264392',
    projectId: 'fierbace-project',
    authDomain: 'fierbace-project.firebaseapp.com',
    storageBucket: 'fierbace-project.firebasestorage.app',
    measurementId: 'G-6L8XV68Z4Z',
  );
}
